const Map<String, String> htmlTestData = <String, String>{
  'a': '<a href="http://www.w3.org/">Hello, World!</a>',
  'abbr': '<abbr>HLO-WRLD</abbr>',
  'b': '<b>Hello, World!<b>Hello, World!<b>Hello, World!</b></b></b>',
  'strong': '<strong>Hello, World!</strong>',
  'big': '<big>Hello, World!<big>Hello, World!</big></big>',
  'blockquote':
      '<blockquote>Hello, World!\nHello, World!\nHello, World!Hello, World!Hello, World!Hello, World!\nHello, World!Hello, World!Hello, World!Hello, World!Hello, World!Hello, World!</blockquote>',
  'br': '<a>Hello,<br />World!</a>',
  'center': '<center>Hello, World!</center><a>xxxxx</a>',
  'code': '<code>Hello, World!</code>',
  'kbd': '<kbd>Hello, World!</kbd>',
  'samp': '<samp>Hello, World!</samp>',
  'tt': '<tt>Hello, World!</tt>',
  'del': '<del>Hello, World!</del>',
  'dfn': '<dfn>Hello, World!</dfn>',
  's': '<s>Hello, World!</s>',
  'strike': '<strike>Hello, World!</strike>',
  'div': '<div>Hello, World!</div>',
  'em': '<em>Hello, World!</em>',
  'i': '<i>Hello, World!</i>',
  'font': '<font size="4" color="red">Hello, World!</font>',
//  'footer': '<footer>Hello, World!</footer>',
  'h1': '<h1>Hello, World!</h1>',
  'h2': '<h2>Hello, World!</h2>',
  'h3': '<h3 align="center">Hello, World!</h3>',
  'h4': '<h4>Hello, World!</h4>',
  'h5': '<h5>Hello, World!</h5>',
  'h6': '<h6>Hello, World!</h6>',
//  'header': '<header>Hello, World!</header>',
  'hr': '<div>Hello</div><hr width="100"/><div>World!</div>',
  'img':
      '<img alt="Hello, World!" src="https://www.baidu.com/img/bd_logo1.png?where=super" align="middle" height="50" border="10" /><a>Hello, World!</a>',
  'img_alt': '<img alt="Hello, World!" src="" width="30"/>',
  'ins': '<ins>Hello, World!</ins>',
  'u': '<u>Hello, World!</u>',
  'mark': '<mark>Hello, World!</mark>',
  'li': '<li>Hello</li>xxx<li>World!</li>',
  'li_ul': '<ul>xxx<li>Hello</li>xxx<li>World!</li>xxx</ul>',
  'li_ol': '<ol><li>Hello</li><li>World!</li></ol>',
  'p': '<p>Hello, World!</p>xxx<p>Hello, World!</p>',
  'pre': '<pre>Hello, World!</pre>',
  'small': '<a>Hello, World!</a><small>Hello, World!</small>',
  'span': '<span>Hello, World!</span>',
  'sub': '<a>Hello, World!</a><sub>Hello, World!</sub>',
  'sup': '<a>Hello, World!</a><sup>Hello, World!</sup>',
  'sub_sup':
      '<p>log<sub>2</sub>(<em>x</em><sup>2</sup> - 6<em>x</em>) = 3 + log<sub>2</sub>(1 - <em>x</em>)</p>',
  'video':
      '<video src="movie.ogg" controls="controls">您的浏览器不支持 video 标签。</video>',
  'video_post':
      '<video src="movie.ogg" poster="https://www.baidu.com/img/bd_logo1.png?where=super" height="100" controls="controls">您的浏览器不支持 video 标签。</video>',
};
