name: router_annotation
description: Flutter Router Annotation.
version: 2.0.0
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/RxReader/router_kit

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
  flutter_lints:
