name: router_annotation
description: Flutter Router Annotation.
version: 1.0.0
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/HollySite/router_kit

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test:

  pedantic:
