name: router_compiler
description: Flutter Router Compiler.
version: 3.0.0
# author: v7lin <v7lin@qq.com>
homepage: https://github.com/RxReader/router_kit

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  router_annotation: ^2.0.0

  analyzer: ^5.2.0
  logging: ^1.0.0
  build: ^2.0.0
  source_gen: ^1.0.0

dev_dependencies:
  test:

  pedantic:
