name: build

on: [push, pull_request]

jobs:
  build_ios:
    name: Build iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: check router_annotation
        run: |
          cd router_annotation/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check router_compiler
        run: |
          cd router_compiler/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check router_api
        run: |
          cd router_api/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: build example
        run: |
          cd example/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter analyze lib
          flutter build ios --no-codesign

  build_android:
    name: Build Android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - name: check router_annotation
        run: |
          cd router_annotation/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check router_compiler
        run: |
          cd router_compiler/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: check router_api
        run: |
          cd router_api/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter pub publish --dry-run
          flutter analyze lib
      - name: build example
        run: |
          cd example/
          flutter pub get
          flutter format --dry-run --set-exit-if-changed .
          flutter analyze lib
          flutter build apk --debug
